class Campus
  CAMPO_MOURAO = "03"
  APUCARANA = "10"
  CORNELIO_PROCOPIO = "02"
  CURITIBA = "01"
  DOIS_VIZINHOS = "07"
  FRANCISCO_BELTRAO = "11"
  GUARAPUAVA = "12"
  LONDRINA = "07"
  MEDIANEIRA = "04"
  PATO_BRANCO = "05"
  PONTA_GROSSA = "06"
  SANTA_HELENA = "13"
  TOLEDO = "09"

end
